# Generated by Django 5.1.5 on 2025-01-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mgame',
            name='image',
            field=models.ImageField(blank=True, upload_to='games/'),
        ),
    ]
