# Generated by Django 5.1.5 on 2025-02-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_mgame_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mgame',
            name='category',
        ),
        migrations.AddField(
            model_name='mgame',
            name='category',
            field=models.ManyToManyField(to='www.mcategory'),
        ),
    ]
