# Generated by Django 5.1.5 on 2025-02-11 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0003_remove_mgame_category_mgame_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mgame',
            name='status',
        ),
        migrations.AlterField(
            model_name='mgame',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mgame',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
