# Generated by Django 5.1.5 on 2025-02-15 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_muserprofile_friends'),
        ('www', '0004_remove_mgame_status_alter_mgame_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mgame',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='mgame',
            name='rating',
        ),
        migrations.AddField(
            model_name='mgame',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.muserprofile'),
        ),
        migrations.AddField(
            model_name='mgame',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='www.mstatus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mgame',
            name='video',
            field=models.FileField(blank=True, upload_to='games/'),
        ),
    ]
