# Generated by Django 5.1.5 on 2025-02-17 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0009_mgame_average_rating_mgame_rating_count_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MFavoriteGame',
        ),
    ]
