# Generated by Django 5.1.5 on 2025-02-21 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0010_delete_mfavoritegame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcomment',
            name='title',
        ),
    ]
