# Generated by Django 5.1.5 on 2025-02-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0013_mimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mimage',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='mimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
