# Generated by Django 5.1.5 on 2025-03-31 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0014_remove_mimage_uploaded_at_alter_mimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mimage',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='www.mgame'),
        ),
    ]
