# Generated by Django 5.1.5 on 2025-02-11 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_muserprofile_slug_alter_muserprofile_description_and_more'),
        ('www', '0004_remove_mgame_status_alter_mgame_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muserprofile',
            name='game',
            field=models.ManyToManyField(blank=True, to='www.mgame'),
        ),
    ]
