# Generated by Django 5.1.5 on 2025-02-11 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_muserprofile_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='muserprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, to='user_profile.muserprofile'),
        ),
    ]
