# Generated by Django 5.1.5 on 2025-02-17 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_teglist_muserprofile_birth_date_teg'),
        ('www', '0010_delete_mfavoritegame'),
    ]

    operations = [
        migrations.CreateModel(
            name='MFavoriteGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='www.mgame')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_games', to='user_profile.muserprofile')),
            ],
            options={
                'unique_together': {('user', 'game')},
            },
        ),
    ]
