# Generated by Django 5.1.5 on 2025-02-19 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_mfavoritegame'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='muserprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='user_profile.muserprofile'),
        ),
        migrations.AlterField(
            model_name='teg',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
