# Generated by Django 5.1.5 on 2025-02-21 12:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_alter_muserprofile_friends_alter_teg_user'),
        ('www', '0011_remove_mcomment_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teg',
            unique_together={('user', 'game')},
        ),
    ]
